name: EasyEconomy
author: ImperaZim
version: 1.0.0
api: 4.0.0
main: ImperaZim\EasyEconomy\Loader

permissions:
 easyeconomy.give.use:
  default: op
 easyeconomy.set.use:
  default: op
 easyeconomy.take.use:
  default: op
